changeLogFile=01_tables/00000_changelog.yaml

url=jdbc:postgresql://postgres-db:5432/cafetin_db
username=cafetin_user
password=cafetin_pass

driver=org.postgresql.Driver
classpath=drivers/postgresql-42.3.0.jar